### ISSUE TITLE
Sugestão para a página /06-estruturas-de-dados/05-sets.html

### ISSUE THREAD

**Issue by villares** [HenriqueAJNB/python-para-todos#4]
Prezado Henrique, obrigado por escrever e compartilhar generosamente este livro!

Hoje em dia "string" (cadeia de caracteres) é um termo raramente traduzido, mas as outras estruturas de dados fundamentais do Python você apresenta com os nomes traduzidos, o que acho perfeito, então minha sugestão é: traduza o nome da seção "Sets" para "Conjuntos"!

**Comment by HenriqueAJNB** [comment]
Oi @villares. Você gostaria de subir estas correções/traduções? Eu posso inclusive colocar seu nome como contribuidor na capa do livro se desejar, como a @camilaccb, que subiu várias correções.

Eu posso montar um guia de contribuição também pra ajudar.

**Comment by HenriqueAJNB** [comment]
Posso colocar você como responsável por essa issue @villares? 👍🏼

**Comment by villares** [comment]
> Posso colocar você como responsável por essa issue @villares? 👍🏼 

Depende de como for o setup no seu guia de contribuição... se for muito complexo eu não consigo me comprometer neste momento. Se fosse só editar um markdown eu conseguiria ajudar mais fácil.
