### ISSUE TITLE
Sugestão para a página /09-modulos/02-modulos-nativos.html

### ISSUE THREAD

**Issue by villares** [HenriqueAJNB/python-para-todos#5]
Existe um esforço de voluntários (temos um grupo no Telegram em `t.me / pybr_i18n`) para traduzir toda a documentação oficial do Python, então a minha sugestão é que você ponha sempre os links para a página em português, neste caso: https://docs.python.org/pt-br/3/library/index.html 

Uma segunda sugestão é adotar "Biblioteca Padrão" para "módulos nativos", e "funções embutidas" para as funções "built-in" que é a convenção adotada pela documentação e também pelo Ramalho no Python Fluente.

**Comment by HenriqueAJNB** [comment]
Oi @villares. Eu faço parte do grupo no Telegram! E de fato, eu não me atentei a isso.

Quer subir esse reapontamento dos links para a doc já traduzida (onde obviamente já existir a tradução)?

**Comment by villares** [comment]
Eu adotaria a url com `pt-br` direto, aí quando ainda não tiver tradução vai estar em inglês como está agora...

**Comment by HenriqueAJNB** [comment]
Eu subi as alterações nesse commit [aqui](https://github.com/HenriqueAJNB/python-para-todos/commit/f7f3f09f5c0e708029080e3c156398068c4ed4ed). Vou adotar esse padrão no livro a partir de agora!
